server:
  port: ${SERVER_PORT}

spring:
  application:
    name: user-microservice
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

api:
  version: v1

# swagger = http://{host}:{port}/{api.version}/template/swagger-ui/index.html
springdoc:
  swagger-ui:
    path: /${api.version}/users/

logging:
  level:
    org:
      springdoc: DEBUG